### ISSUE TITLE
NHostApolloProvider + Next.js requires "PrivateRoute" HOC 

### ISSUE THREAD

**Issue by brunocrosier** [nhost/react-apollo#4]
With the current setup, the `<NHostApolloProvider>` component requires Next.js users to wrap any pages where they are using `useQuery`, `useMutation` or `useSubscription` with a `PrivateRoute` HOC (e.g https://github.com/nhost-examples/nextjs-apollo/blob/main/components/private-route.jsx)

This is leads to a suboptimal developer experience, because `PrivateRoute` isn't mentioned in Nhost's docs, and the component isn't exported from `@nhost/react-apollo`

It's also not the best experience to have to wrap pages in a HOC, and the [official Next.js + Apollo examples](https://github.com/vercel/next.js/tree/canary/examples/with-apollo) don't use this strategy

I wanted to create a PR, but actually I think this requires a lot of changes and planning, which should be discussed beforehand.

As a temporary / short-term solution, I recommend:

- export a `PrivateRoute` component directly from the `@nhost/react-apollo` package
- add documentation about how this should work for Next.js

As a medium/long-term solution, I think it would make sense to consolidate `@nhost/react-auth` and `@nhost/react-apollo` into a single package, and export a single `<NhostProvider  />` component which will look something like this:

```
<NhostProvider projectID="xlokuk9q">
<App />
</NhostProvider>
```

Behind the scenes, we can easily use the `projectID` value to create the backend URL and graphQL endpoint URL

The `NhostProvider` component should take inspiration from [here](https://github.com/vercel/next.js/blob/canary/examples/with-apollo/lib/apolloClient.js) to ensure that pages don't need to be wrapped in a `PrivateRoute` component in the future

**Comment by elitan** [comment]
I think the reason why [official Next.js + Apollo examples](https://github.com/vercel/next.js/tree/canary/examples/with-apollo) does not use a similar `PrivateRoute` approach is because it does not handle auth.

I generally think this discussion should be in the [`nhost/react-auth`](https://github.com/nhost/react-auth) repository because `nhost/react-auth` could be used with this `nhost/react-apollo` package but also for [`nhost/react-urql`](https://github.com/nhost/react-urql) and other feature graphql clients.

The code in the PrivateRoute component is similar to the code from other examples for Next.js like [here](https://github.com/vercel/next.js/blob/canary/examples/auth0/pages/index.js), [here](https://github.com/vercel/next.js/blob/canary/examples/with-cookie-auth-fauna/pages/profile.js) and [here](https://github.com/vercel/next.js/blob/canary/examples/with-next-auth/components/nav.js).

I like the idea of adding the `PrivateRoute` component to the `@nhost/react-auth` package. We just need to figure out how to make the [loading and redirect message](https://github.com/nhost-examples/nextjs-apollo/blob/main/components/private-route.jsx#L11-L16) customizable.

We had the `@nhost/react-auth` and @nhost/react-apollo` packages merged before in `react-nhost` but that was limited because developers wanted to use other graphql clients than Apollo.

```js
<NhostProvider projectID="xlokuk9q">
<App />
</NhostProvider>
```

This code looks good, but it could be confusing to allow for `projectID` and custom domains (non `backend-xxx.nhost.app` domains). Also we're not pushing the `projectID` variable anywhere in the Nhost console - which also could lead to confusion. 

**In summery I think we should:**

- Close this issue
- Open up a new issue in the [`nhost/react-auth`](https://github.com/nhost/react-auth) where we discuss how to implement the `PrivateRoute` component into that package
- In the new issue, discuss how to customize the loading and redirect text and possible rename the `PrivateRoute` component to something that's more specific to Next.js. Or if we could use the same component for both Next.js and [React Router](https://github.com/ReactTraining/react-router).
